[emby]
# Whether to run in test mode only. Only shows logs without modifying the Rotten Tomatoes (critic) rating.
# You can test before every real run, and switch to no once you're satisfied with the result.
# Backing up the Emby data directory before a real run is recommended.
dry_run = yes

# Emby URL, example: http://192.168.1.2:8096/
host =

# API key, can be set in the Emby admin panel. Example: 15e83402916944c56785923a198ce5db
api_key =

# The page in Emby for configuring user permissions, the URL is on top. Example: b35c78a9cb712343a101cbc50d9a9fcc
user_id =

# Number of bgm.tv requests allowed per run
req_limit = 50

# Total emby item count limit, sorted by date added
item_limit = 50

# Emby item starting position (skip the first N), sorted by date added
start_index = 0

# Specify a media library; if not specified, filtering is based on genre. Multiple libraries can be separated with commas.
# At least one of library and genre must be specified
library_name =

# Genre keyword filter, usually no need to change. (taken from Emby home page > Libraries > top menu: Genres)
genre = 动画

# Video type limit: if only searching for anime series, keep only Series
types = Movie,Series,Video

# Proxy for requests, leave empty if not needed. http://127.0.0.1:7890
http_proxy =
